import {API_URL, API_VERSION} from './config';

export type IAPIName =
  | 'BALANCE_SHEET'
  | 'COMPREHENSIVE_INCOME_STATEMENTS'
  | 'STATEMENTS_OF_CASH_FLOW'
  | 'STATEMENTS_OF_RED_FLAGS'
  | 'EXCHANGE_RATES';

export interface IAPINameConstant {
  BALANCE_SHEET: IAPIName;
  COMPREHENSIVE_INCOME_STATEMENTS: IAPIName;
  STATEMENTS_OF_CASH_FLOW: IAPIName;
  EXCHANGE_RATES: IAPIName;
  //STATEMENTS_OF_RED_FLAGS: IAPIName;
}

export const APIName: IAPINameConstant = {
  BALANCE_SHEET: 'BALANCE_SHEET',
  COMPREHENSIVE_INCOME_STATEMENTS: 'COMPREHENSIVE_INCOME_STATEMENTS',
  STATEMENTS_OF_CASH_FLOW: 'STATEMENTS_OF_CASH_FLOW',
  EXCHANGE_RATES: 'EXCHANGE_RATES',
};

export const APIURL = {
  BALANCE_SHEET: `${API_URL}/${API_VERSION}/balance-sheet`,
  COMPREHENSIVE_INCOME_STATEMENTS: `${API_URL}/${API_VERSION}/comprehensive-income`,
  STATEMENTS_OF_CASH_FLOW: `${API_URL}/${API_VERSION}/cash-flow`,
  EXCHANGE_RATES: `${API_URL}/${API_VERSION}/exchange-rates`,

  WEBSITE_RESERVE: 'https://api.tidebit-defi.com/public/reserve',
};
